/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import beans.Departamento;
import com.placeholder.PlaceHolder;
import conexion_bd.ConexionSQL;
import java.io.IOException;
import java.sql.SQLException;
import dao.DAO;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import tools.IOTools;

/**
 *
 * @author alt-j
 */
public class Departamentos extends javax.swing.JFrame {

    IOTools txtFormat = new IOTools();
    TableRowSorter trs;
    PlaceHolder holder;
    ConexionSQL con;
    Menu menu;
    DAO dao;

    /**
     * Creates new form Departamentos
     */
    public Departamentos(Menu menu) throws SQLException, IOException {
        initComponents();

        holder = new PlaceHolder(txtBuscar, " Filtrar por nombre...");
        this.setLocationRelativeTo(null);

        con = ConexionSQL.getInstance();
        dao = new DAO(con.getConnection());

        txtFormat.limitar_texto(txtBuscar, 50);
        btnActualizar.requestFocus();

        Color color = new Color(245, 245, 245);
        jScrollPane3.getViewport().setBackground(color);

        dao.deptos.getAll(tblDepartamentos);
        this.menu = menu;
        
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                menu.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDepartamentos = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de departamentos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(243, 243, 243));
        jButton3.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/srch.png"))); // NOI18N
        jButton3.setText("Consulta");
        jButton3.setToolTipText("Consulta individual");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 110, 40));

        jLabel1.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel1.setText("Departamentos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 280, 50));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 50, 40));

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 320, 40));

        btnInsertar.setBackground(new java.awt.Color(245, 245, 245));
        btnInsertar.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/new2.png"))); // NOI18N
        btnInsertar.setToolTipText("Nuevo Departamento");
        btnInsertar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 40, 40));

        btnBorrar.setBackground(new java.awt.Color(245, 245, 245));
        btnBorrar.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/delete2.png"))); // NOI18N
        btnBorrar.setToolTipText("Eliminar Departamento");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 40, 40));

        btnActualizar.setBackground(new java.awt.Color(245, 245, 245));
        btnActualizar.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/edit.png"))); // NOI18N
        btnActualizar.setToolTipText("Actualizar Departamento");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 40, 40));

        tblDepartamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "   ID Departamento", "   Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDepartamentos.setGridColor(new java.awt.Color(153, 204, 255));
        tblDepartamentos.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tblDepartamentos);
        if (tblDepartamentos.getColumnModel().getColumnCount() > 0) {
            tblDepartamentos.getColumnModel().getColumn(0).setPreferredWidth(120);
            tblDepartamentos.getColumnModel().getColumn(1).setPreferredWidth(450);
        }

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 570, 260));

        jButton2.setBackground(new java.awt.Color(243, 243, 243));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/return2.png"))); // NOI18N
        jButton2.setToolTipText("Regresar al menú de inicio");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 70, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pexels-photo-262367.jpeg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        txtFormat.filter(tblDepartamentos, txtBuscar, 1);
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        try {
            Insertar_Departamento ins = new Insertar_Departamento(tblDepartamentos);
            ins.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Deducciones.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Departamentos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        DefaultTableModel dm = (DefaultTableModel) tblDepartamentos.getModel();

        if (dm.getRowCount() > 0) {
            int r = tblDepartamentos.getSelectedRow();
            if (r >= 0) {
                int ans = JOptionPane.showConfirmDialog(null,
                        "Se eliminará el Departamento\n¿Deseas continuar?", "Advertencia", 2);

                if (ans == JOptionPane.YES_OPTION) {
                    int id = Integer.valueOf(String.valueOf(dm.getValueAt(r, 0)));
                    if (dao.deptos.delete(id)) {
                        txtFormat.borrar_tabla(tblDepartamentos);
                        dao.deptos.getAll(tblDepartamentos);
                    } else {
                        JOptionPane.showMessageDialog(null, "Ocurrió un error al eliminar el departamento", "Error", 0);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione el registro a eliminar", "No hay registros seleccionados", 2);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay registros para eliminar", "Error", 0);
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        DefaultTableModel dm = (DefaultTableModel) tblDepartamentos.getModel();

        if (dm.getRowCount() > 0) {
            int r = tblDepartamentos.getSelectedRow();
            if (r >= 0) {
                int idDepartamento = Integer.valueOf(String.valueOf(dm.getValueAt(r, 0)));

                Actualizar_Departamento act;
                try {
                    act = new Actualizar_Departamento(tblDepartamentos, idDepartamento);
                    act.setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Deducciones.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Departamentos.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione el registro a actualizar", "No hay registros seleccionados", 2);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay registros para actualizar", "Advertencia", 2);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        MasInfoDepto info;
        try {
            info = new MasInfoDepto();
            info.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Puestos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Departamentos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Departamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Departamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Departamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Departamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Departamentos(null).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Departamentos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Departamentos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblDepartamentos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}