/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import conexion_bd.ConexionSQL;
import dao.DAO;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Miguel
 */
public class MasInfoHorario extends javax.swing.JFrame {
    int idHorario;
    ConexionSQL con;
    String datos[];
    DAO dao;
    
    public MasInfoHorario(int idHorario) throws SQLException, IOException {
        initComponents();
        this.setLocationRelativeTo(null);
        
        jScrollPane1.getViewport().setBackground(new Color(243,243,243));
        jPanel2.requestFocus();
        
        con = ConexionSQL.getInstance();
        dao = new DAO(con.getConnection());
        this.idHorario = idHorario;
        
        datos = dao.horarios.getH(idHorario);
        this.setData();
    }
    
    public void setData() {
        if(datos != null) {            
            txtIdH.setText(String.format("%03d", idHorario));
            
            txtHI.setText(datos[0]);
            txtHF.setText(datos[1]);
            
            String dias[] = datos[2].split(",");
            for(int i=0; i<dias.length; i++) {
                switch(dias[i]) {
                    case "Lun":
                        chbLun.setSelected(true);
                        break;
                    case "Mar":
                        chbMar.setSelected(true);
                        break;
                    case "Mie":
                        chbMie.setSelected(true);
                        break;
                    case "Jue":
                        chbJue.setSelected(true);
                        break;
                    case "Vie":
                        chbVie.setSelected(true);
                        break;
                    case "Sab":
                        chbVie.setSelected(true);
                        break;
                    case "Dom":
                        chbDom.setSelected(true);
                        break;
                }
            }
            
            txtIdEmpleado.setText(datos[3]);
            dao.horarios.getAll(tblHorarios, Integer.valueOf(datos[4]), idHorario);
        } else
            JOptionPane.showMessageDialog(null, "Error al consultar los datos del horario", "Error", 0);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHorarios = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIdH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHF = new javax.swing.JTextField();
        txtIdEmpleado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        chbDom = new javax.swing.JCheckBox();
        chbLun = new javax.swing.JCheckBox();
        chbMie = new javax.swing.JCheckBox();
        chbMar = new javax.swing.JCheckBox();
        chbJue = new javax.swing.JCheckBox();
        chbVie = new javax.swing.JCheckBox();
        chbSab = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalles de horario");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(252, 252, 252));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Horarios relacionados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        tblHorarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Hr. Inicio", "Hr. Fin", "Días"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHorarios.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblHorarios);
        if (tblHorarios.getColumnModel().getColumnCount() > 0) {
            tblHorarios.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblHorarios.getColumnModel().getColumn(1).setPreferredWidth(80);
            tblHorarios.getColumnModel().getColumn(2).setPreferredWidth(80);
            tblHorarios.getColumnModel().getColumn(3).setPreferredWidth(188);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 430, 290));

        jPanel2.setBackground(new java.awt.Color(252, 252, 252));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos generales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jLabel2.setText("ID Horario:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 60, 30));

        txtIdH.setEditable(false);
        jPanel2.add(txtIdH, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 110, -1));

        jLabel3.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jLabel3.setText("H. Inicio:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, 30));

        txtHI.setEditable(false);
        jPanel2.add(txtHI, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 55, -1));

        jLabel4.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jLabel4.setText("H. Fin:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, 30));

        txtHF.setEditable(false);
        jPanel2.add(txtHF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 55, -1));

        txtIdEmpleado.setEditable(false);
        jPanel2.add(txtIdEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 326, -1));

        jLabel5.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jLabel5.setText("Empleado:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        chbDom.setText("DO");
        chbDom.setEnabled(false);

        chbLun.setText("LU");
        chbLun.setEnabled(false);

        chbMie.setText("MI");
        chbMie.setEnabled(false);

        chbMar.setText("MA");
        chbMar.setEnabled(false);

        chbJue.setText("JU");
        chbJue.setEnabled(false);

        chbVie.setText("VI");
        chbVie.setEnabled(false);

        chbSab.setText("SA");
        chbSab.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(chbDom)
                .addGap(16, 16, 16)
                .addComponent(chbLun)
                .addGap(16, 16, 16)
                .addComponent(chbMar)
                .addGap(16, 16, 16)
                .addComponent(chbMie)
                .addGap(16, 16, 16)
                .addComponent(chbJue)
                .addGap(16, 16, 16)
                .addComponent(chbVie)
                .addGap(16, 16, 16)
                .addComponent(chbSab)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbDom)
                    .addComponent(chbJue)
                    .addComponent(chbMie)
                    .addComponent(chbMar)
                    .addComponent(chbLun)
                    .addComponent(chbVie)
                    .addComponent(chbSab))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 388, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 430, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pexels-photo-1353938.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-450, 0, 920, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasInfoHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasInfoHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasInfoHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasInfoHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MasInfoHorario(0).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MasInfoHorario.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(MasInfoHorario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chbDom;
    private javax.swing.JCheckBox chbJue;
    private javax.swing.JCheckBox chbLun;
    private javax.swing.JCheckBox chbMar;
    private javax.swing.JCheckBox chbMie;
    private javax.swing.JCheckBox chbSab;
    private javax.swing.JCheckBox chbVie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHorarios;
    private javax.swing.JTextField txtHF;
    private javax.swing.JTextField txtHI;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtIdH;
    // End of variables declaration//GEN-END:variables
}
