/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import beans.Puesto;
import com.placeholder.PlaceHolder;
import conexion_bd.ConexionSQL;
import dao.DAO;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import tools.IOTools;

/**
 *
 * @author alt-j
 */
public class Puestos extends javax.swing.JFrame {

    IOTools txtFormat = new IOTools();
    TableRowSorter trs;
    PlaceHolder holder;
    ConexionSQL con;
    Menu menu;
    DAO dao;

    /**
     * Creates new form Puestos
     */
    public Puestos(Menu menu) throws SQLException, IOException {
        initComponents();
        holder = new PlaceHolder(txtBuscar, "Buscar por nombre");
        this.setLocationRelativeTo(null);

        con = ConexionSQL.getInstance();
        dao = new DAO(con.getConnection());

        txtFormat.limitar_texto(txtBuscar, 80);
        btnActualizar.requestFocus();

        Color color = new Color(245, 245, 245);
        jScrollPane3.getViewport().setBackground(color);

        dao.puestos.getAll(tblPuestos);
        this.menu = menu;
        
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                menu.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar2 = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPuestos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel1.setText("Puestos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 280, 50));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 50, 40));

        txtBuscar2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscar2KeyTyped(evt);
            }
        });
        getContentPane().add(txtBuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 380, 40));

        btnInsertar.setBackground(new java.awt.Color(245, 245, 245));
        btnInsertar.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/new2.png"))); // NOI18N
        btnInsertar.setToolTipText("Insertar Puesto");
        btnInsertar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 40, 40));

        btnBorrar.setBackground(new java.awt.Color(245, 245, 245));
        btnBorrar.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/delete2.png"))); // NOI18N
        btnBorrar.setToolTipText("Borrar Puesto");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 40, 40));

        btnActualizar.setBackground(new java.awt.Color(245, 245, 245));
        btnActualizar.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/edit.png"))); // NOI18N
        btnActualizar.setToolTipText("Actaulizar Puesto");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 40, 40));

        tblPuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Puesto", "Nombre", "Salario Minimo", "Salario Maximo", "Estatus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPuestos.setGridColor(new java.awt.Color(153, 204, 255));
        tblPuestos.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tblPuestos);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 600, 260));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pexels-photo-136413.jpeg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscar2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscar2KeyTyped
        txtFormat.filter(tblPuestos, txtBuscar, 1);
    }//GEN-LAST:event_txtBuscar2KeyTyped

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        try {
            Insertar_Puesto ins = new Insertar_Puesto(tblPuestos);
            ins.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Deducciones.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Deducciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        DefaultTableModel dm = (DefaultTableModel) tblPuestos.getModel();

        if (dm.getRowCount() > 0) {
            int r = tblPuestos.getSelectedRow();
            if (r >= 0) {
                int ans = JOptionPane.showConfirmDialog(null,
                        "Se eliminará el Puesto\n¿Deseas continuar?", "Advertencia", 2);

                if (ans == JOptionPane.YES_OPTION) {
                    int id = Integer.valueOf(String.valueOf(dm.getValueAt(r, 0)));
                    if (dao.puestos.delete(id)) {
                        txtFormat.borrar_tabla(tblPuestos);
                        dao.puestos.getAll(tblPuestos);
                    } else {
                        JOptionPane.showMessageDialog(null, "Ocurrió un error al eliminar el puesto", "Error", 0);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione el registro a eliminar", "No hay registros seleccionados", 2);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay registros para eliminar", "Error", 0);
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        DefaultTableModel dm = (DefaultTableModel) tblPuestos.getModel();

        if (dm.getRowCount() > 0) {
            int r = tblPuestos.getSelectedRow();
            if (r >= 0) {
                int idPuesto = Integer.valueOf(String.valueOf(dm.getValueAt(r, 0)));
                String nombre = String.valueOf(dm.getValueAt(r, 1));
                double salarioMin = Double.valueOf(String.valueOf(dm.getValueAt(r, 2)));
                double salarioMax = Double.valueOf(String.valueOf(dm.getValueAt(r, 3)));

                Puesto puesto = new Puesto(idPuesto, nombre, salarioMin, salarioMax);

                Actualizar_Puesto act;
                try {
                    act = new Actualizar_Puesto(tblPuestos, puesto);
                    act.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Deducciones.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Deducciones.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione el registro a actualizar", "No hay registros seleccionados", 2);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay registros para actualizar", "Advertencia", 2);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Puestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Puestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Puestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Puestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Puestos(null).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Puestos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Puestos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblPuestos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtBuscar1;
    private javax.swing.JTextField txtBuscar2;
    // End of variables declaration//GEN-END:variables
}
